export enum DONATION_STATUS {
  ENVIADA_A_ONG = 'ENVIADA_A_ONG',
  ACEPTADA_POR_ONG = 'ACEPTADA_POR_ONG',
  RECHAZADA_POR_ONG = 'RECHAZADA_POR_ONG',
  ASIGNADA_A_PROYECTO = 'ASIGNADA_A_PROYECTO',
  RECIBIDA_POR_PROYECTO = 'RECIBIDA_POR_PROYECTO',
  ASIGNADA_A_BENEFICIARIO = 'ASIGNADA A BENEFICIARIO',
  ENTREGADA_A_BENEFICIARIO = 'ENTREGADA_A_BENEFICIARIO',
  EJECUTADA_EN_PROYECTO = 'EJECUTADA_EN_PROYECTO'
}


export const PROJECT_STATUS = {
  CREATED: "CREATED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
};

export const BENEFICIARY_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};
