export enum DonationStatus {
  ENVIADA_A_ONG = 'ENVIADA_A_ONG',
  ACEPTADA_POR_ONG = 'ACEPTADA_POR_ONG',
  RECHAZADA_POR_ONG = 'RECHAZADA_POR_ONG',
  ASIGNADA_A_PROYECTO = 'ASIGNADA_A_PROYECTO',
  RECIBIDA_POR_PROYECTO = 'RECIBIDA_POR_PROYECTO',
  EJECUTADA_EN_PROYECTO = 'EJECUTADA_EN_PROYECTO',
  ENTREGADA_A_BENEFICIARIO = 'ENTREGADA_A_BENEFICIARIO'
}